[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ziontools"
dependencies = [
    "pandas",
    "roifile",
    "scipy",
    "opencv-python",
    "scikit-learn",
    "matplotlib"
]
version='0.2.0'

[tool.setuptools.packages]
find = {}
